[[redirects]]
  from = "/orderss"
  to = "http://ec2-18-229-105-100.sa-east-1.compute.amazonaws.com/orders"
  status = 200
  force = true

[[redirects]]
  from = "/products"
  to = "http://ec2-18-229-105-100.sa-east-1.compute.amazonaws.com/products"
  status = 200
  force = true

[dev]
  port = 8888

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = false

[build.processing.js]
  bundle = true
  minify = false

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true