[[redirects]]
  from = "/orderss"
  to = "http://ec2-18-229-105-100.sa-east-1.compute.amazonaws.com/orders"
  status = 200
  force = true

[[redirects]]
  from = "/products"
  to = "http://ec2-18-229-105-100.sa-east-1.compute.amazonaws.com/products"
  status = 200
  force = true